import * as service from './service.js';

export default {
  id: 'sections',
  title: '栏目',
  order: 500,
  view: () => import('./view.jsx'),
  // 一组同级实体，每条有标识，用户会想改其中一条或删其中一条 → 集合资源，CRUD 五操作齐备
  resource: 'section',
  actions: [
    {
      id: 'section.list',
      cli: ['section', 'list'],
      http: ['GET', '/api/sections'],
      summary: '列出全部栏目（含字段数与条目数）',
      flags: {},
      run: () => service.listSections(),
      render: (d) => service.renderSectionList(d),
    },
    {
      id: 'section.templates',
      cli: ['section', 'templates'],
      http: ['GET', '/api/sections/templates'],
      summary: '列出内置栏目模板（求职 / 密钥）',
      flags: {},
      run: () => service.listTemplates(),
      render: (d) => service.renderTemplates(d),
    },
    {
      id: 'section.get',
      cli: ['section', 'get'],
      http: ['GET', '/api/sections/:ref'],
      summary: '读单个栏目（id 或标题都接受），含完整字段字典',
      args: ['ref'],
      flags: {},
      run: (ctx) => service.getSection(ctx.ref),
      render: (d) => service.renderSectionGet(d),
    },
    {
      id: 'section.dump',
      cli: ['section', 'dump'],
      http: ['GET', '/api/sections/:ref/dump'],
      summary: '一个栏目的全部信息：字段台账 + 所有条目 + 每个条目的未填清单',
      args: ['ref'],
      flags: { mask: { type: 'boolean', hint: '密文字段打码显示（投屏/截图时用）' } },
      run: (ctx) => service.dump(ctx.ref, ctx),
      render: (d) => service.renderSectionDump(d),
    },
    {
      id: 'section.add',
      cli: ['section', 'add'],
      http: ['POST', '/api/sections'],
      summary: '新建栏目；--template 从内置模板起步（求职 / 密钥）。重复 id 报 CONFLICT',
      args: ['id'],
      flags: {
        title: { type: 'string', hint: '栏目标题' },
        template: { type: 'string', hint: 'job|secret' },
        description: { type: 'string' },
        order: { type: 'number', default: 50 },
        fields: { type: 'json', hint: '字段定义数组的 JSON' },
        groups: { type: 'json', hint: '分组定义数组的 JSON' },
        'dry-run': { type: 'boolean' },
      },
      run: (ctx) => service.addSection(ctx),
      render: (d) => service.renderSectionChange(d),
    },
    {
      id: 'section.update',
      cli: ['section', 'update'],
      http: ['PATCH', '/api/sections/:ref'],
      summary: '改栏目（PATCH 语义：只改传入项）。字段台账可用 add-field / remove-field / fields / fill；--kv 标成 KV 表',
      args: ['ref'],
      flags: {
        title: { type: 'string' },
        description: { type: 'string' },
        order: { type: 'number' },
        titleField: { type: 'string', hint: '用哪个字段做条目名' },
        titleLabel: { type: 'string' },
        kv: { type: 'boolean', hint: '标成 KV 表（密钥那种）；取消写 --kv=false' },
        fields: { type: 'json', hint: '整体替换字段字典' },
        groups: { type: 'json', hint: '整体替换分组' },
        'add-field': { type: 'json', hint: '{"key":"x","label":"X","type":"text"}，可重复' },
        'remove-field': { type: 'array', hint: '字段 key，可重复传（一次删一个）' },
        fill: { type: 'kv', hint: '字段=normal|optional|avoid，可重复。optional 不必填、avoid 填了可能减分，两者都不计入完整度；改回照常填传 normal' },
        'dry-run': { type: 'boolean' },
      },
      run: (ctx) => service.updateSection(ctx.ref, ctx),
      render: (d) => service.renderSectionChange(d),
    },
    {
      id: 'section.remove',
      cli: ['section', 'remove'],
      http: ['DELETE', '/api/sections/:ref'],
      summary: '删栏目（连带其条目）。栏目非空时必须加 --force。目标不存在时报 NOT_FOUND，不静默成功',
      args: ['ref'],
      flags: {
        force: { type: 'boolean', hint: '确认连带删除栏目下的条目' },
        'dry-run': { type: 'boolean' },
      },
      run: (ctx) => service.removeSection(ctx.ref, ctx),
      render: (d) => service.renderSectionChange(d),
    },
  ],
};
